### ISSUE TITLE
Can't launch the program on my computer

### ISSUE THREAD

**Issue by cp287-zz** [eoakley/artifacthelper#25]
When I'm trying to run program nothing happenes. 

At log file:
Traceback (most recent call last):
  File "E:\Users\Gamer\AppData\Local\Artifact Helper\Artifact_Helper.launch.pyw", line 31, in <module>
    from artifact_helper import main
  File "E:\Users\Gamer\AppData\Local\Artifact Helper\pkgs\artifact_helper.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

My system: windows 7, two monitors, resolutions: 1920x1080 and 1600x1200. Artifact on first one with resolution 1440x960 16:10 borderless.

**Comment by eoakley** [comment]
Try running it manually.
Run this on Windows PowerShell:
```
cd "E:\Users\Gamer\AppData\Local\Artifact Helper\Python"
E:
.\python.exe ..\Artifact_Helper.launch.pyw
```

**Comment by cp287-zz** [comment]
It doesn't work. Same error at log: (now with real messages in angle-brackets)
Traceback (most recent call last):
File "E:\Users\Gamer\AppData\Local\Artifact Helper\Artifact_Helper.launch.pyw", line 31, in < module >
from artifact_helper import main
File "E:\Users\Gamer\AppData\Local\Artifact Helper\pkgs\artifact_helper.py", line 7
< !DOCTYPE html >
^
SyntaxError: invalid syntax

**Comment by Miojo** [comment]
Python files shouldn't have "< !DOCTYPE html >" on them. 
Please verify the integrity of your file ( "E:\Users\Gamer\AppData\Local\Artifact Helper\pkgs\artifact_helper.py" ) comparing it with  [artifact_helper.py](https://github.com/eoakley/artifacthelper/blob/master/artifact_helper.py)

**Comment by cp287-zz** [comment]
Sorry, it was my fault with downloading.
I fix it but mostly nothing changed:
log file:

Traceback (most recent call last):
  File "E:\Users\Gamer\AppData\Local\Artifact Helper\Artifact_Helper.launch.pyw", line 31, in < module >
    from artifact_helper import main
  File "E:\Users\Gamer\AppData\Local\Artifact Helper\pkgs\artifact_helper.py", line 127, in < module >
    tiers = fix_dict(read_tier_text(urlopen('https://raw.githubusercontent.com/eoakley/artifactscraping/master/tier_list.txt').read(), raw=True))
TypeError: read_tier_text() got an unexpected keyword argument 'raw'

**Comment by Miojo** [comment]
You also need to update the [tier_list_scrape.py](https://github.com/eoakley/artifacthelper/blob/master/tier_list_scrape.py) file to the last version. The raw argument was added in a recent commit.

**Comment by cp287-zz** [comment]
ok, on a second monitor it find the cards, thanks
